update 6 18_12_2025

diff --git a/.github/workflows/ManualGithubActions.yaml b/.github/workflows/ManualGithubActions.yaml
--- a/.github/workflows/ManualGithubActions.yaml
+++ b/.github/workflows/ManualGithubActions.yaml
@@ -13,7 +13,6 @@ on:
           - smoke
           - regression
 
-
 jobs:
   Manual-GitHub-Actions-Testing:
     runs-on: ubuntu-latest
@@ -48,96 +47,184 @@ jobs:
           mkdir -p allure-results
           export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/PyPwBehave/test-automation-tool/src
 
-      
-          behave PyPwBehave/test-automation-toolsrc/features/Development_python.feature \
+          behave PyPwBehave/test-automation-tool/src/features/Development_python.feature \
             --no-capture \
             -f allure_behave.formatter:AllureFormatter \
             -o allure-results \
             -D browser=${{ matrix.browser }} \
             -t @${{ inputs.tag }}
 
-#         export PYTHONPATH=${{ github.workspace }}/PyPwBehave/test-automation-tool/src
-#      - name: Run Behave tests (DEBUG)
-#        run: |
-#          echo "== Workspace =="
-#          pwd
-#          echo ""
-#
-#          echo "== Estrutura do projeto =="
-#          ls -R PyPwBehave || true
-#          echo ""
-#
-#          echo "== Rodando Behave SEM TAG =="
-#          mkdir -p allure-results
-#
-#          behave \
-#            PyPwBehave/test-automation-tool/src/features \
-#            -f allure_behave.formatter:AllureFormatter \
-#            -o allure-results
-#
-#          echo ""
-#          echo "== Arquivos gerados no allure-results =="
-#          ls -lah allure-results || true
-
-#      - name: Run Behave tests
-#        run: |
-#          mkdir -p allure-results
-#          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/PyPwBehave/test-automation-tool/src
-#          behave \
-#            --no-capture \
-#            -f allure_behave.formatter:AllureFormatter \
-#            -o allure-results \
-#            -D browser=${{ matrix.browser }} \
-#            -t @${{ inputs.tag }} \
-#            PyPwBehave/test-automation-tool/src/features
-
       - name: Generate Allure Report
         if: always()
         working-directory: PyPwBehave/test-automation-tool
         run: |
           allure generate allure-results -o allure-report --clean
-      
 
       - name: Debug allure-results content
         if: always()
         run: |
           echo "Arquivos gerados:"
           find PyPwBehave/test-automation-tool/allure-results -type f
-      
-      
 
-      #      - name: Upload Allure HTML Report
-#        if: always()
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: allure-report-${{ matrix.browser }}
-#          path: allure-report/**
-#          retention-days: 2
-
-      - name: Upload Allure HTML Report
+      - name: Upload Allure HTML Report (artifact)
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: allure-report-${{ matrix.browser }}
           path: PyPwBehave/test-automation-tool/allure-report
 
+      - name: Deploy Allure Report to GitHub Pages
+        if: always()
+        uses: peaceiris/actions-gh-pages@v6
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: PyPwBehave/test-automation-tool/allure-report
+          publish_branch: gh-pages
+          user_name: github-actions
+          user_email: github-actions@github.com
 
 
 
-
-          #      - name: Download Test Results
-#        if: always()
-#        uses: actions/download-artifact@v4
+#name: Manual GitHub Actions Demo Tests - Behave + Playwright
+#run-name: ${{ github.actor }} is testing with Behave + Playwright 🚀
+#
+#on:
+#  workflow_dispatch:
+#    inputs:
+#      tag:
+#        description: Qual a tag?
+#        required: true
+#        type: choice
+#        options:
+#          - login
+#          - smoke
+#          - regression
+#
+#
+#jobs:
+#  Manual-GitHub-Actions-Testing:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        browser: [chromium, firefox, webkit]
+#      fail-fast: false
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#
+#      - name: Setup Python 3.12
+#        uses: actions/setup-python@v4
 #        with:
-#          name: results-${{ matrix.browser }}
-#          path: ./reports
-
-
-      
-
-    
-
-
-
-
-         
+#          python-version: '3.12'
+#
+#      - name: Setup Node.js 20
+#        uses: actions/setup-node@v3
+#        with:
+#          node-version: '20'
+#
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install -r requirements.txt
+#          playwright install --with-deps
+#          npm install -g allure-commandline
+#
+#      - name: Run Behave tests
+#        run: |
+#          mkdir -p allure-results
+#          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/PyPwBehave/test-automation-tool/src
+#
+#
+#          behave PyPwBehave/test-automation-toolsrc/features/Development_python.feature \
+#            --no-capture \
+#            -f allure_behave.formatter:AllureFormatter \
+#            -o allure-results \
+#            -D browser=${{ matrix.browser }} \
+#            -t @${{ inputs.tag }}
+#
+##         export PYTHONPATH=${{ github.workspace }}/PyPwBehave/test-automation-tool/src
+##      - name: Run Behave tests (DEBUG)
+##        run: |
+##          echo "== Workspace =="
+##          pwd
+##          echo ""
+##
+##          echo "== Estrutura do projeto =="
+##          ls -R PyPwBehave || true
+##          echo ""
+##
+##          echo "== Rodando Behave SEM TAG =="
+##          mkdir -p allure-results
+##
+##          behave \
+##            PyPwBehave/test-automation-tool/src/features \
+##            -f allure_behave.formatter:AllureFormatter \
+##            -o allure-results
+##
+##          echo ""
+##          echo "== Arquivos gerados no allure-results =="
+##          ls -lah allure-results || true
+#
+##      - name: Run Behave tests
+##        run: |
+##          mkdir -p allure-results
+##          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/PyPwBehave/test-automation-tool/src
+##          behave \
+##            --no-capture \
+##            -f allure_behave.formatter:AllureFormatter \
+##            -o allure-results \
+##            -D browser=${{ matrix.browser }} \
+##            -t @${{ inputs.tag }} \
+##            PyPwBehave/test-automation-tool/src/features
+#
+#      - name: Generate Allure Report
+#        if: always()
+#        working-directory: PyPwBehave/test-automation-tool
+#        run: |
+#          allure generate allure-results -o allure-report --clean
+#
+#
+#      - name: Debug allure-results content
+#        if: always()
+#        run: |
+#          echo "Arquivos gerados:"
+#          find PyPwBehave/test-automation-tool/allure-results -type f
+#
+#
+#
+#      #      - name: Upload Allure HTML Report
+##        if: always()
+##        uses: actions/upload-artifact@v4
+##        with:
+##          name: allure-report-${{ matrix.browser }}
+##          path: allure-report/**
+##          retention-days: 2
+#
+#      - name: Upload Allure HTML Report
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: allure-report-${{ matrix.browser }}
+#          path: PyPwBehave/test-automation-tool/allure-report
+#
+#
+#
+#
+#
+#          #      - name: Download Test Results
+##        if: always()
+##        uses: actions/download-artifact@v4
+##        with:
+##          name: results-${{ matrix.browser }}
+##          path: ./reports
+#
+#
+#
+#
+#
+#
+#
+#
+#
+#
